#! /bin/bash
#SBATCH -A see200002p       # specify the project or allocation number
#SBATCH -J myjob                # Job name
#SBATCH -N 1                    # Number of nodes, not cores (16 cores/node)
#SBATCH -n 4# Number of cores requested in total
#SBATCH -p GPU-shared #GPU-shared partition
#SBATCH --gpus=v100-32:4 #allocation 1 v100 gpu(i.e =v100-32:5 allocates 5GPUS)"
./dijkstra_100_ACC_gpu
